[package]
name = "zerosni"
version = "0.1.0"
edition = "2024"

[profile.release]
panic = "abort"

[dependencies]
arc-swap = "1"
compact_str = { version = "0.9", features = ["serde"] }
dns-parser = "0.8"
tls-parser = "0.12"
monoio = { version = "0.2", default-features = false, features = ["async-cancel", "bytes", "iouring", "utils", "macros"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
libc = "0.2"
serde = { version = "1", features = ["derive"] }
socket2 = { version = "0.5", features = ["all"] }
struson = { version = "0.6", features = ["serde"] }
url = "2"
moka = { version = "0.12", features = ["future"] }
signal-hook = "0.3"
