[package]
name = "zerosni"
version = "0.1.0"
edition = "2024"

[profile.release]
panic = "abort"

[dependencies]
arc-swap = "1"
compact_str = { version = "0.9", features = ["serde"] }
dns-parser = "0.8"
tls-parser = "0.12"
tokio = { version = "1", features = ["fs", "io-std", "io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-rustls = "0.26"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
libc = "0.2"
rustls = { version = "0.23", default-features = false, features = ["std", "tls12", "logging", "aws_lc_rs"] }
rustls-pemfile = "2"
x509-cert = { version = "0.2", features = ["builder", "hazmat"] }
der = { version = "0.7", features = ["std", "alloc", "oid"] }
spki = "0.7"
p256 = { version = "0.13", features = ["ecdsa", "pkcs8"] }
sec1 = "0.7"
sha2 = { version = "0.10", features = ["oid"] }
rand = "0.8"
const-oid = "0.9"
webpki-roots = "0.26"
serde = { version = "1", features = ["derive"] }
socket2 = { version = "0.6", features = ["all"] }
struson = { version = "0.6", features = ["serde"] }
url = "2"
moka = { version = "0.12", features = ["future"] }
signal-hook = "0.3"
time = "0.3"
